#用于保存资源的路径static，以及用于截图工具的路径tool
[path]
ffmpeg_path = "D:\\GoProject\\simple_douyin\\tool\\ffmpeg.exe"
static_source_path = "D:\\GoProject\\simple_douyin\\static"

#记录当前服务器的ip和启动端口号，当前服务器的ip用于生成对应的视频链接地址
[server]
ip = "192.168.10.14"
port = 8080

#关系型数据库配置
[mysql]
host = "127.0.0.1"
port = 3306
database = "douyin"
username = "root"
password = "123456"
charset = "utf8mb4"
parse_time = true
loc = "Local"

#非关系数据库配置
[redis]
host = "127.0.0.1"
port = 6379
database = 0



